In [133]:
import numpy as np
import time
import random

import plotly
import plotly.graph_objects as go
import plotly.express as px

import plotly.io as pio

### Упражнение 1

На одном графике изобразите время затраченное на вычисление с использованием массивов numpy и стандартных списков в питоне.  
Для более точных результатов замеряйте время выполнения функции несколько раз и усредняйте. 
* Используйте функцию `z = 2*x**2 + 4*y`
* Перемножение матриц размера n на n

In [152]:
def harvesting_time(n):
    '''
    Функция возвращает списки со временем выполнения вычислений c матрицами 
    всех размеров в диапазоне (от 1 до n) при исполлзовании python или numpy.
    '''
    lst_p = []
    lst_n = []
    for number in range(1, n):
        lst_p = counting_time(func_p, number, lst_p)
        lst_n = counting_time(func_n, number, lst_n)
    return lst_p, lst_n

def counting_time(func_type, number, lst):
    '''
    Функция вычисляет время, затраченное на вычисление с матрицами рамера n*n
    '''
    start = time.time()
    func_type(number)
    lst.append(time.time() - start)
    return lst

def func_p(n):
    '''Функция вычисляет посроедством python'''
    return sum_matrix(
        mult_matrix_scal(nn_python(n), 2), mult_matrix_scal(y_python(n), 4)
    )

def nn_python(n):
    '''Произведение матрицы на саму себя с посредством python'''
    N = matrix_gauss_p(n)
    X = matrix_p(n, 0)
    for row_idx in range(len(N)):
        for col_idx in range(len(N[0])):
            for col_row_idx in range(len(N)):
                X[row_idx][col_idx] += (
                    N[row_idx][col_row_idx]
                ) * (
                    N[col_row_idx][col_idx]
                )
    return X
    
def matrix_gauss_p(n):
    '''
    Формирование матрицы с нормально распределенными значениями внутри 
    посредством python
    '''
    return [[random.gauss(0, 1) for _ in range(n)] for _ in range(n)]

def matrix_p(n, value):
    '''
    Формирование матрицы с любыми одинаковыми значениями внутри 
    посредством python
    '''
    return [[value for _ in range(n)] for _ in range(n)]

def y_python(n):
    '''
    Формирование дополнительной матрицы Y с нормально распределенными значениями 
    внутри посредством python
    '''
    return matrix_gauss_p(n)

def mult_matrix_scal(matrix, value):
    '''Умножение матрицы на скалярную величину в python'''
    for row in range(len(matrix)):
        for col in range(len(matrix[0])):
            matrix[row][col] = matrix[row][col] * value
    return matrix

def sum_matrix(matrix_1, matrix_2):
    '''Сложение матриц в python'''
    for row in range(len(matrix_1)):
        for col in range(len(matrix_1[0])):
            matrix_1[row][col] = matrix_1[row][col] * matrix_2[row][col]
    return matrix_1

def func_n(n):
    '''Вычисление формулы посредством numpy'''
    return 2*nn_numpy(n) + 4*y_numpy(n) 

def nn_numpy(n):
    '''
    Формирование матрицы с нормально распределенными величинами внутри
    размерности n*n в numpy
    '''
    X = np.random.normal(size=np.square(n)).reshape(n, n)
    return X.dot(X)

def y_numpy(n):
    '''
    Формирование дополнительной матрицы Y с нормально распределенными величинами
    внутри размерности n*n в numpy
    '''
    Y = np.random.normal(size=np.square(n)).reshape(n, n)
    return Y

n = 200

%time lst_p, lst_n = harvesting_time(n)

CPU times: user 1min 43s, sys: 13.6 s, total: 1min 56s
Wall time: 1min 41s


In [153]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=[idx for idx, num in enumerate(lst_p)], 
        y=lst_p, mode='lines', name='py_time'
    )
)

fig.add_trace(
    go.Scatter(
        x=[idx for idx, num in enumerate(lst_n)], 
        y=lst_n, mode='lines', name='nu_time'
    )
)

fig.show()

### Упражнение 2
* Создайте массив чисел от 2 до 75. Выведите только нечётные. 
* Присвойте нечётным числам этого массива значение -1.



In [170]:
def odd_eq_neg_one(start, stop):
    ar = np.arange(start, stop+1)
    ar_odd = (ar[ar % 2 != 0])
    ar[ar % 2 != 0] = -1
    return ar, ar_odd

ar, ar_odd = odd_eq_neg_one(2, 75)
print('Нечетные элементы =', ar_odd)
print('Обновленный массив =', ar)

Нечетные элементы = [ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53 55 57 59 61 63 65 67 69 71 73 75]
Обновленный массив = [ 2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1 24 -1
 26 -1 28 -1 30 -1 32 -1 34 -1 36 -1 38 -1 40 -1 42 -1 44 -1 46 -1 48 -1
 50 -1 52 -1 54 -1 56 -1 58 -1 60 -1 62 -1 64 -1 66 -1 68 -1 70 -1 72 -1
 74 -1]


### Упражнение 3

* Найдите в документации функцию, которая удаляет из одного массива элементы, которые есть в другом. 
* Приведите примеры использования.

In [161]:
ar_01 = np.arange(10) # массив в котором ищем
ar_02 = np.arange(10, step=2) # массив, значений которого ищем в другом массиве

ar_03 = np.delete(ar_01, ar_02)
print('ar_01 =', ar_01, '\n', 'ar_02 =', ar_02, '\n', 'ar_01 без ar_02 =', ar_03)

ar_01 = [0 1 2 3 4 5 6 7 8 9] 
 ar_02 = [0 2 4 6 8] 
 ar_01 без ar_02 = [1 3 5 7 9]


### Упражнение 4

* Создайте случайную квадратную матрицу случайного размера от 10 до 100. 
* Найдите максимум и сумму элементов.
* Поделите каждый элемент матрицы на максимум.
* Отнимите от каждой строки матрицы среднее по строке.
* Замените максимальное значение на -1.

In [189]:
# генерим размерность матрицы
dim = np.random.randint(10, 100, 1)
dim

array([12])

In [203]:
# генерим матрицу
matrix = np.random.rand(dim[0], dim[0])
# выводим только нулевой вектор, чтобы экономить место
matrix[0]

array([0.17168653, 0.00960036, 0.8037309 , 0.46782905, 0.42755674,
       0.21875688, 0.41999727, 0.73756951, 0.38628388, 0.03278906,
       0.05672026, 0.24250467])

In [204]:
# находим максимум
maximum = np.max(matrix)
maximum

0.993668348977612

In [205]:
# находим сумму всех элементов матрицы
sum_elem = np.sum(matrix)
sum_elem

73.13186278010134

In [206]:
# делим на максимум каждый элемент матрицы
matrix = matrix / maximum
matrix[0]

array([0.17278052, 0.00966154, 0.80885228, 0.47081005, 0.43028113,
       0.2201508 , 0.42267349, 0.7422693 , 0.38874528, 0.03299799,
       0.05708168, 0.24404991])

In [220]:
# вычисляем среднее по каждой строке матрицы
mx_mean = np.mean(matrix, axis=1)
mx_mean

array([0.33336283, 0.28834921, 0.55009947, 0.599423  , 0.55512206,
       0.63161282, 0.43798321, 0.5813778 , 0.50965869, 0.46493382,
       0.59942676, 0.58180523])

In [221]:
# делаем reshape вектора средних, чтобы отнимать элементы построчно
matrix_1 = matrix - np.mean(matrix, axis=1).reshape(-1, 1)
matrix_1[0:2]

array([[-0.16058231, -0.32370129,  0.47548944,  0.13744722,  0.0969183 ,
        -0.11321203,  0.08931066,  0.40890647,  0.05538245, -0.30036484,
        -0.27628115, -0.08931292],
       [ 0.02617776, -0.23930157,  0.19291662, -0.10006404, -0.18006705,
         0.5197632 , -0.20243924, -0.07410974, -0.12064156,  0.5075954 ,
        -0.12683699, -0.20299279]])

In [222]:
# создаем маску для поиска максимального элемента. Применяем маску к матрице.
# присваиваем бывшему максимум значение -1.
print(np.max(matrix_1))
matrix_1[matrix_1 == np.max(matrix_1)] = -1
matrix_1[0:2]

0.5197632040881079


array([[-0.16058231, -0.32370129,  0.47548944,  0.13744722,  0.0969183 ,
        -0.11321203,  0.08931066,  0.40890647,  0.05538245, -0.30036484,
        -0.27628115, -0.08931292],
       [ 0.02617776, -0.23930157,  0.19291662, -0.10006404, -0.18006705,
        -1.        , -0.20243924, -0.07410974, -0.12064156,  0.5075954 ,
        -0.12683699, -0.20299279]])

### Упражнение 5
* Напишите функцию, которая берет многомерный вещественный массив с пропущенными значениями (np.nan) и возвращает его копию с заполненными пропусками (заменять средним значением всех элементов массива). Если в массиве одни пропущенные значения, заполните их нулями.

In [269]:
def create_matrix(rows, cols):
    '''
    Создаем матрицу с желаемым количеством строк и столбцов. 
    Делаем значения np.nan как пожелаем.
    '''
    matrix = np.random.randint(0, 10, size=(rows, cols)).astype('float64')
    matrix[matrix % 3 == 0] = np.nan
    return fill_nan(matrix)

def fill_nan(matrix):
    '''
    Проверяем на наличие не nan в матрице. Если такие значения есть, 
    то заполняем nan средним матрицы. Если обратная ситуация - 
    заполняем nan нулями. 
    '''
    if False in np.isnan(matrix):
        matrix[np.isnan(matrix)] = np.nanmean(matrix)
    else:
        matrix = np.zeros_like(matrix)
    return matrix

rows = 5
cols = 6

matrix = create_matrix(rows, cols)
matrix

array([[5.        , 4.57142857, 4.57142857, 4.57142857, 5.        ,
        5.        ],
       [1.        , 5.        , 7.        , 4.57142857, 8.        ,
        7.        ],
       [4.57142857, 4.57142857, 2.        , 4.57142857, 5.        ,
        2.        ],
       [7.        , 2.        , 7.        , 1.        , 8.        ,
        4.57142857],
       [5.        , 2.        , 4.57142857, 2.        , 5.        ,
        5.        ]])

### Упражнение 6
* Напишите функцию которая нормализирует заданный numpy-массив, так чтобы его значения лежали в интервале $[0, 1]$.

In [278]:
def create_matrix(rows, cols):
    '''Создаем матрицу'''
    matrix = np.random.randint(0, 100, size=(rows, cols)).astype('float64')
    return normalization(matrix)

def normalization(matrix):
    '''Нормализуем и возвращаем матрицу'''
    max_ = np.max(matrix)
    min_ = np.min(matrix)
    matrix_ = (matrix - min_) / (max_ - min_)
    return matrix_

rows = 5
cols = 6

norm_matrix = create_matrix(rows, cols)
print('Min =', np.min(norm_matrix), '\nMax =', np.max(norm_matrix))
norm_matrix

Min = 0.0 
Max = 1.0


array([[0.70103093, 0.        , 0.43298969, 0.15463918, 0.88659794,
        0.25773196],
       [0.09278351, 0.54639175, 0.19587629, 0.79381443, 0.60824742,
        0.89690722],
       [0.1443299 , 0.12371134, 0.49484536, 0.65979381, 0.57731959,
        0.46391753],
       [0.94845361, 0.55670103, 0.12371134, 0.59793814, 0.32989691,
        0.18556701],
       [1.        , 0.49484536, 0.10309278, 0.77319588, 0.82474227,
        0.09278351]])

### Упражнение 7
* Запишите numpy-array в файл.
* Считайте numpy-array из файла.

In [280]:
# записываем
np.save('./ar_0', np.random.normal(size=12).reshape(3, -1))
# читаем
np.load('./ar_0.npy')

array([[-1.43297633, -0.97241682, -1.58645766,  1.12663425],
       [-0.64383364, -0.00874669,  0.00856159, -0.89735513],
       [-0.09239657, -0.13375763, -1.19555905,  0.84320227]])

### Упражнение 8
* Создайте случайный массив
* Найдите в массиве элемент ближайший к данному

In [289]:
def create_ar(rows, cols):
    '''
    Создаем массив и число, ближайшее к которому значение 
    будет искаться в массиве
    '''
    matrix_raveled = np.random.random((rows, cols)).ravel() # ravel для поиска
    random_number = np.random.random()
    return find_nearest(matrix_raveled, random_number)

def find_nearest(matrix_raveled, random_number):
    '''
    Поиск индекса наименьшего по модулю значения разности каждого 
    элемента с данным числом
    '''
    idx = np.abs(matrix_raveled - random_number).argmin()
    return random_number, matrix_raveled[idx]

rows = 5
cols = 6

number, ar_number = create_ar(rows, cols)
print('Дано число =', number, '\nБлижайший элемент в массиве = ', ar_number)

Дано число = 0.2722766891537648 
Ближайший элемент в массиве =  0.30273431231963854


### Упражнение 9

* Напишите функцию, которая возвращает  $n \times m$ целочисленную матрицу с заданным значением на границах матрицы и с заданным значением внутри

In [296]:
def create_matrix(rows, cols, ext_num, in_num):
    '''
    Создаем единичную матрицу простоты заполнения. Периметр заполняем слайсами.
    '''
    matrix = np.ones(shape=(rows, cols)).astype('int32')*ext_num
    matrix[1:-1, 1:-1] = in_num
    return matrix

rows = 5
cols = 6
ext_num = 5
in_num = 4

create_matrix(rows, cols, ext_num, in_num)


array([[5, 5, 5, 5, 5, 5],
       [5, 4, 4, 4, 4, 5],
       [5, 4, 4, 4, 4, 5],
       [5, 4, 4, 4, 4, 5],
       [5, 5, 5, 5, 5, 5]], dtype=int32)

### Упражнение 10
* Напишите функцию, которая сортирует строки данной матрицы по значениям заданного столбца в порядке убывания. 

In [303]:
def create_matrix(rows, cols, col_to_sort):
    '''Создаем матрицу из целых чисел'''
    matrix = np.random.randint(1, 10, (rows, cols))
    return sort_matrix(matrix, col_to_sort)

def sort_matrix(matrix, col_to_sort):
    '''
    Сортировка матрицы через выбор необходимой колонки, получения 
    отсортированного массива индексов данной колонки, применения маски к матрице 
    и разворота в обратном порядке
    '''
    matrix_ = matrix[matrix[:, col_to_sort].argsort()][::-1]
    return matrix, matrix_

rows = 5
cols = 6
col_to_sort = 4  

# вызов функции
matrix, matrix_sorted = create_matrix(rows, cols, col_to_sort)
print(matrix, '\n\n', matrix_sorted)

[[9 7 4 8 6 8]
 [3 9 2 6 6 3]
 [7 4 4 4 2 7]
 [5 7 1 2 4 2]
 [2 4 5 2 7 5]] 

 [[2 4 5 2 7 5]
 [3 9 2 6 6 3]
 [9 7 4 8 6 8]
 [5 7 1 2 4 2]
 [7 4 4 4 2 7]]


### Упражнение 11

* Напишите функцию, которая создает двоичную матрицу шахматной доски с заданным shape

Пример 4x4:
```python
[[0, 1, 0, 1],
 [1, 0, 1, 0],
 [0, 1, 0, 1],
 [1, 0, 1, 0]]
```

In [324]:
def create_matrix(rows, cols):
    '''Создаем нулевую матрицу. Присваиваем 1 через слайсы'''
    matrix = np.zeros(shape=(rows, cols))
    matrix[::2, 1::2] = matrix[1::2, ::2] = 1
    return matrix

rows = 5
cols = 8

create_matrix(rows, cols)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

### Упражнение 12
* Напишите игру [life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life), используя массивы numpy.
* Визуализируйте интерактивно ее результаты.

